<?xml version="1.0"?>
<package format="3">
  <name>kairos</name>
  <version>1.0.0</version>
  <description>KAIROS: 4D Scene Graphs for Periodic Flow Dynamics. The flow and
  temporal contribution, built as a library on top of (but separate from)
  Hydra.</description>

  <maintainer email="iacopomcatalano@gmail.com">Iacopo Catalano</maintainer>
  <license>MIT</license>

  <buildtool_depend>cmake</buildtool_depend>

  <depend>hydra</depend>
  <depend>config_utilities</depend>
  <depend>eigen</depend>
  <depend>kimera_pgmo</depend>
  <depend>spark_dsg</depend>
  <depend>spatial_hash</depend>
  <depend>nlohmann-json-dev</depend>
  <depend>libpcl-all-dev</depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
